apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- varreference.yaml
resources:
- nodejsapp-feature-controller.yml
- nodejsapp-service.yml

configMapGenerator:	
- name: nodejs-test-cm
  literals:	
    - branch=develop
    - build=20191025
    - external_ip=9.46.76.24
    - external_port=3000

vars:
- name: BRANCH_NAME
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.branch
- name: BUILD_NUMBER
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.build
- name: EXTERNAL_IP
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.external_ip   
- name: EXTERNAL_PORT
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.external_port 