nameSuffix: -develop-20191025
commonLabels:
  app: nodejsapp-develop-20191025
images:
- name: PLACEHOLDER_DOCKER_REPO/default/petsapp
  newName: 9.46.76.93:5000/nodejs/sample-rest-api2-pets
  newTag: "0.1"
resources:
- ../../base
- configMap.yaml
patchesStrategicMerge:
- test.yaml
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nodejsapp
  spec:
    template:
      spec:
        containers:
        - name: "nodejsapp"
          env:
          - name: VCAP_APPLICATION
            value: "{\"application_id\":\"8a4bf70b-c759-4b3e-ab9b-f0db3867d23e\",\"application_name\":\"joycepets1\",\"application_uris\":[\"joycepets1.mybluemix.net\"],\"application_version\":\"4c855fec-0798-4b02-9af9-2238808a529d\",\"cf_api\":\"https://api.ng.bluemix.net\",\"host\":\"0.0.0.0\",\"instance_id\":\"d762904e-c413-4afb-7f68-c01c\",\"instance_index\":0,\"limits\":{\"disk\":1024,\"fds\":16384,\"mem\":256},\"name\":\"joycepets1\",\"port\":8080,\"space_id\":\"f92f2e12-08bf-4389-b0a7-d95d8e9fede5\",\"space_name\":\"yuecchen@cn.ibm.com\",\"uris\":[\"joycepets1.mybluemix.net\"],\"version\":\"4c855fec-0798-4b02-9af9-2238808a529d\"}"
                  
configMapGenerator:	
- name: nodejs-test-cm
  literals:	
    - branch=develop
    - build=20191025

vars:
- name: BRANCH_NAME
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.branch
- name: BUILD_NUMBER
  objref:
    kind: ConfigMap
    name: nodejs-test-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.build

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nodejsapp
  patch: |-
    - op: replace
      path: /spec/selector
      value: 
            matchLabels:
              app: nodejsapp-develop-20191025
              pod: nodejsapp-develop-20191025
    
    - op: replace
      path: /spec/template/metadata/labels
      value:
            app: nodejsapp-develop-20191025
            pod: nodejsapp-develop-20191025
    - op: replace
      path: /spec/template/metadata/name
      value: nodejsapp-develop-20191025
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: nodejsapp-develop-20191025