apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-local-storage-postgresql-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.postgresql.storage.capacity }}
  local:
    path: {{ .Values.postgresql.storage.local_path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.postgresql.storage.hostname }}
  persistentVolumeReclaimPolicy: {{ .Values.postgresql.storage.policy }}
  storageClassName: {{ .Release.Name }}-local-storage-postgresql
  volumeMode: Filesystem

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: {{ .Release.Name }}-postgresql
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-local-storage-postgresql
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
