proxy_ip: 9.46.74.217

k8s:
  deployment_api: apps/v1
  ingress_api: extensions/v1beta1

postgresql:
  uid: 1000
  schema: api
  username: authenticator
  password: mysecretpassword
  table_name: incidents
  db_role:  web_anon
  port: 5432
  sql_file: db-init.sql
  sql_path: /tmp/init-db
  storage:
    hostname: "9.46.74.243"
    capacity: 15Gi
    local_path: /k8s/data/postgres
    policy: Recycle

postgrest:
  port: 3000
  ingress_path: rest
  jwt_secret: cJzKWZRJCFWHbJ6O7RUEebpZWx37BV7i
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidG9kb191c2VyIn0.pF7fhh4XfCz72LN3YQh-g0GmDy-3vZjQA7AgCD1w9dk

openresty:
  port: 80
  ingress_path: incidents
