- name: Create argo-events namespace
  k8s:
    name: argo-events
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /root/.kube/config
- name: install argo workflow - cluster-role
  k8s:
    state: present
    definition: 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: argo-events-default-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: argo-events 
    kubeconfig: /root/.kube/config
- name: github-access-secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        secret: "{{ events.github_access_token  | b64encode  }}"
        token:  "{{ events.github_access_secret | b64encode  }}"
      kind: Secret
      metadata:
        name: github-access
        namespace: argo-events
      type: Opaque
    kubeconfig: /root/.kube/config
- get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-events/master/examples/event-sources/github.yaml
    dest: "{{playbook_dir}}/argo-events/github-event-source.cm-ee.yaml"
- get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-events/master/examples/gateways/github.yaml
    dest: "{{playbook_dir}}/argo-events/github-gateway.yaml"
- template:
    src:  files/github-event-source.patch.j2
    dest: /tmp/github-event-source.patch
- template:
    src:  files/github-gateway.patch.j2
    dest: /tmp/github-gateway.patch
- name: patch github-event-source.cm-ee.yaml
  patch:
    src: /tmp/github-event-source.patch
    dest: "{{playbook_dir}}/argo-events/github-event-source.cm-ee.yaml"
- name: patch github-gateway.yaml
  patch:
    src: /tmp/github-gateway.patch
    dest: "{{playbook_dir}}/argo-events/github-gateway.yaml" 
- name: create github event source
  k8s:
    src: "{{playbook_dir}}/argo-events/github-event-source.cm-ee.yaml"
    state: present
    namespace: argo-events
    kubeconfig: /root/.kube/config
- name: create github gateway
  k8s:
    src: "{{playbook_dir}}/argo-events/github-gateway.yaml"
    state: present
    namespace: argo-events
    kubeconfig: /root/.kube/config

