- hosts: master
  vars:
    argocd_server_external: 9.46.76.93
    nfs_src: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
  tasks:
    - name: Clone nfs provider
      git:
        repo: 'https://github.com/kubernetes-incubator/external-storage.git'
        dest: "{{playbook_dir}}/external-storage"
        depth: 1
        update: yes
        force: yes       
    - name: patch nfs provider
      patch:
        src: "{{playbook_dir}}/files/nfs-provider.patch"
        basedir: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
    - name: install nfs provider
      k8s:                  ## yum install -y python2-openshift.noarch  in advance
        state: present
        src: "{{nfs_src}}/{{item}}"
        kubeconfig: /root/.kube/config
        namespace: default
      with_list:
        - class.yaml
        - claim.yaml
        - psp.yaml 
        - statefulset.yaml
    - name: get argocd install yaml
      get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/v1.2.3/manifests/install.yaml
        dest: "{{playbook_dir}}/argocd/argocd-1.2.3-install.yaml"
    - name: prepare argocd patch
      template:
        src:  files/argocd-1.2.3.patch.j2
        dest: /tmp/argocd-1.2.3.patch
    - name: patch argocd install yaml
      patch:
        src: /tmp/argocd-1.2.3.patch
        basedir: "{{playbook_dir}}/argocd"
    - name: Create argocd namespace
      k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/.kube/config 
    - k8s:
        state: present
        src: "{{playbook_dir}}/argocd/argocd-1.2.3-install.yaml"
        kubeconfig: /root/.kube/config
        namespace: argocd
    - name: argocd client
      get_url:
        url: https://github.com/argoproj/argo-cd/releases/download/v1.2.3/argocd-linux-amd64
        dest: /usr/local/bin/argocd
        mode: 755
    - name: check argocd client
      shell: |
          argocd help
      register: std
    - debug:
        var: std.stdout_lines
    - debug:
        var: std.stderr_lines          